In [ ]:
#pip install mlxtend

In [6]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [14]:
transactions = [
    ['Milk', 'Butter', 'Bread'],
    ['Milk', 'Bread'],
    ['Bread', 'Butter', 'Eggs'],
    ['Milk', 'Eggs'],
    ['Bread', 'Butter', 'Juice']    
]

In [19]:
te = TransactionEncoder()
te_array = te.fit_transform(transactions) #.transform(transactions)

te.columns_

df_transactions = pd.DataFrame(te_array, columns=te.columns_)
df_transactions

   Bread  Butter   Eggs  Juice   Milk
0   True    True  False  False   True
1   True   False  False  False   True
2   True    True   True  False  False
3  False   False   True  False   True
4   True    True  False   True  False

In [33]:
frequent_itemsets = apriori(df_transactions,
                         min_support = 0.4,
                         use_colnames = True)

In [41]:
rules = association_rules(frequent_itemsets,
                          metric="confidence",
                          min_threshold=0.4)

final_table = rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']]

display(final_table)

           antecedents          consequents  support  confidence      lift
0   frozenset({Bread})  frozenset({Butter})      0.6    0.750000  1.250000
1  frozenset({Butter})   frozenset({Bread})      0.6    1.000000  1.250000
2   frozenset({Bread})    frozenset({Milk})      0.4    0.500000  0.833333
3    frozenset({Milk})   frozenset({Bread})      0.4    0.666667  0.833333

In [44]:
current_cart = frozenset({'Milk'})

recommendations = final_table[final_table['antecedents'] == current_cart]

recommendations

         antecedents         consequents  support  confidence      lift
3  frozenset({Milk})  frozenset({Bread})      0.4    0.666667  0.833333